### ISSUE TITLE
Neo4J

### ISSUE THREAD

**Issue by shuchirinamdar** [aman-srivastava/SNA4Slack#14]
Research Neo4J as an option to save results generated by NetworkX if building a graph in real-time is  highly time consuming

**Comment by nikhil108** [comment]
Created VM instance on google cloud and completed the setup for Neo4J. Created a document with details and research for considering it as an option to save results generated by NetworkX.

**Comment by shuchirinamdar** [comment]
Dropped plans to implement intermediate buffer database. The team will work on improvements to optimize graph building process.
