### ISSUE TITLE
Generate D3 graph using NetworkX data

### ISSUE THREAD

**Issue by aman-srivastava** [aman-srivastava/SNA4Slack#25]

**Comment by shuchirinamdar** [comment]
Carry forward to Sprint 6

**Comment by aman-srivastava** [comment]
D3 graph is being displayed, generated from NetworkX/MongoDb collection, available by clicking "I'mFeeling Lucky" link on the homepage below:
http://amansrivastava.me/SNA4Slack/html/ltr/vertical-menu-template/search-page.html
