### ISSUE TITLE
Add team-subscription based graph generation

### ISSUE THREAD

**Issue by abhimanyudogra** [aman-srivastava/SNA4Slack#35]
Adding another kind of graph generation. Users will be connected based on the teams they share.

**Comment by nikhil108** [comment]
Looks good to me. Graph generation is working as designed displaying the connected users through different teams in which they are common.
Closeness, betweenness and degree centralities are calculated accurately and exceptions are handled efficiently. Corner cases like single node scenarios are taken care with an appropriate message.

**Comment by shuchirinamdar** [comment]
Verified and approve addition
